### ISSUE TITLE
可以使用CI/CD 的思想来让Uploader更加强大

### ISSUE THREAD

**Issue by jingyuexing** [FortuneDayssss/BilibiliUploader#30]
比如 指定目录并且指定投稿类型，设定时间。都使用yaml文件配置好
```yaml
config:
  - project: # 可以设置多个项目
    type: "video|audio|image" # 投稿类型分为视频投稿 音频投稿 图片投稿
    workspace: "" # 视频的目录
    title: "" #发布的标题
    desc: "" # 描述性文字
    clock:  # 定时发布的时间
```
